import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { composeDream } from '@/lib/services/dream-service'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export const maxDuration = 300

// GET /api/mist/dreams — her dream journal (latest first, optional ?kind=)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const kind = searchParams.get('kind') || undefined
    const limit = Math.min(Math.max(Number(searchParams.get('limit')) || 20, 1), 50)

    const dreams = await db.dream.findMany({
      where: kind ? { kind } : {},
      orderBy: { createdAt: 'desc' },
      take: limit,
    })

    return NextResponse.json({ dreams })
  } catch (error) {
    console.error('Dream GET error:', error)
    return NextResponse.json({ error: 'Failed to retrieve dreams' }, { status: 500 })
  }
}

// POST /api/mist/dreams — compose a dream NOW from the last 24h of her life
// (kind defaults to 'requested'). The narrative is generated by her own
// dreaming mind — the client never supplies dream content.
export async function POST(request: NextRequest) {
  try {
    const body = (await request.json().catch(() => ({}))) as { kind?: 'requested' | 'nightly' | 'idle' }
    const dream = await composeDream(body.kind ?? 'requested')
    return NextResponse.json({ dream })
  } catch (error) {
    console.error('Dream POST error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to compose dream' },
      { status: 500 }
    )
  }
}
